### ISSUE TITLE
today，v1.19  is no longer work

### ISSUE THREAD

**Issue by lkmvip** [truedread/netflix-1080p#90]
are there other similar applications？

**Comment by Lightmani** [comment]
Yes.
Same as you.
Failed to load viedo.

**Comment by NDS7EN** [comment]
Same as you.

**Comment by ym52000000** [comment]
same as you   always loading  can't play

**Comment by lzkbloodmage** [comment]
Having same issue too. Somehow it works again if I only tick "5.1 audio" and untick "select best bitrate"

**Comment by rvpn** [comment]
not working anymore today. sayonara

**Comment by zhangdongpo** [comment]
same as you

**Comment by hankshrader** [comment]
same loading forever

**Comment by GJG666** [comment]
今天v.19就不能用了..

**Comment by zhangdongpo** [comment]
![image](https://user-images.githubusercontent.com/15242207/81471601-dba93980-9224-11ea-96a2-a59e3b67ec54.png)
report a error,who can solve it

**Comment by GJG666** [comment]
> ![图片](https://user-images.githubusercontent.com/15242207/81471601-dba93980-9224-11ea-96a2-a59e3b67ec54.png)
> 报告错误，谁可以解决
对插件进行如下设置：只勾选“ 5.1音频”并取消勾选“选择最佳比特率。此方法暂时可用，

**Comment by zhangdongpo** [comment]
> > ![图片](https://user-images.githubusercontent.com/15242207/81471601-dba93980-9224-11ea-96a2-a59e3b67ec54.png)
> > 报告错误，谁可以解决
> > 对插件进行如下设置：只勾选“ 5.1音频”并取消勾选“选择最佳比特率"。此方法暂时可用。


I tried it a few times and it still doesn't work

**Comment by GJG666** [comment]
> > > ![图片](https://user-images.githubusercontent.com/15242207/81471601-dba93980-9224-11ea-96a2-a59e3b67ec54.png)
> > > 报告错误，谁可以解决
> > > 对插件进行如下设置：只勾选“ 5.1音频”并取消勾选“选择最佳比特率"。此方法暂时可用。
> 
> I tried it a few times and it still doesn't work

![image](https://user-images.githubusercontent.com/36781028/81471790-3e4f0500-9226-11ea-9d0e-1c9aa4706cee.png)
![image](https://user-images.githubusercontent.com/36781028/81471792-48710380-9226-11ea-9c9a-72b6544452ec.png)
我这样设置是可以的

**Comment by zhangdongpo** [comment]
> > > > ![图片](https://user-images.githubusercontent.com/15242207/81471601-dba93980-9224-11ea-96a2-a59e3b67ec54.png)
> > > > 报告错误，谁可以解决
> > > > 对插件进行如下设置：只勾选“ 5.1音频”并取消勾选“选择最佳比特率"。此方法暂时可用。
> > 
> > 
> > I tried it a few times and it still doesn't work
> 
> ![image](https://user-images.githubusercontent.com/36781028/81471792-48710380-9226-11ea-9c9a-72b6544452ec.png)
> 我进行图片中所示的设置是可以的


I ’m on macOS, I just reset it a little bit, it ’s okay now, thank you

**Comment by EnriqCG** [comment]
Activating 5.1 audio solves the problem 👍

**Comment by jasoncgc** [comment]
Even I activating 5.1 audio, still cannot load....

**Comment by lkmvip** [comment]
Some videos do not provide 5.1 channels, so this option has limitations

**Comment by JamesBlandford** [comment]
we probably need to incorporate jsSHA into the extension. i'll see if it works when i do that

**Comment by JamesBlandford** [comment]
The issue is fixed with #89

**Comment by GJG666** [comment]
> we probably need to incorporate jsSHA into the extension. i'll see if it works when i do that

how can i do that,could you teach me something

**Comment by GJG666** [comment]
> The issue is fixed with #89

![image](https://user-images.githubusercontent.com/36781028/81497139-298a7400-92ef-11ea-95f5-11f55faf046d.png)
i don't know what can i do about this

**Comment by lkmvip** [comment]
> The issue is fixed with #89

no, not fix

**Comment by GJG666** [comment]
> 该问题已由[＃89](https://github.com/truedread/netflix-1080p/pull/89)修复[](https://github.com/truedread/netflix-1080p/pull/89)

![image](https://user-images.githubusercontent.com/36781028/81497474-4627ab80-92f1-11ea-9900-36a1bdb66d71.png)
Even after using these codes to cover the original code, an error still occurs

**Comment by Johunn** [comment]
The video works when I ve activated the 5.1 but this is in 720p not 1080p anymore...

**Comment by GJG666** [comment]
> 当我激活5.1时，该视频可以工作，但现在是720p，而不是1080p ...



> 当我激活5.1时，该视频可以工作，但现在是720p，而不是1080p ...

I can watch 1080, as long as the network speed is ok

**Comment by GJG666** [comment]
> 当我激活5.1时，该视频可以工作，但现在是720p，而不是1080p ...

I can watch 1080, as long as the network speed is ok

**Comment by 13XxM1CHA3lxX37** [comment]
1.19 works for me when enabling 5.1. Funny enough I stumbled around this when the Firefox version stopped working yesterday
https://imgur.com/0bb693ed-b663-477f-9b77-31b7044523e1
https://i.imgur.com/MrOepyu.png

**Comment by alienx2** [comment]
Now it working. i think i did remove extension then re-install extension and check both 5.1 and best bitrate in option.

**Comment by lzkbloodmage** [comment]
Seems like the player updated to 6.0023.161.011. Not sure if that affects the extension? And if so, how do we patch/update the 1080p.js file included in the repo? I don't understand the code

**Comment by coxackie** [comment]
So, I applied the workaround in #89 and reinstalled the extension but I still get frozen videos. Anyone else still having the issue?

**Comment by GJG666** [comment]
> 因此，我在[＃89中](https://github.com/truedread/netflix-1080p/pull/89)应用了解决方法，然后重新安装了扩展程序，但仍然收到冻结的视频。还有其他人有这个问题吗？

me too

**Comment by userofryzen** [comment]
the same

**Comment by ihanash** [comment]
it does not work

**Comment by lorderheller** [comment]
anyone know a fix with 2.0 audio videos, works perfectly with videos which have 5.1 audio available

for example all new 2019-2020 releases work which have 5.1 audio, older releases with 2.0 audio only dont work

**Comment by koresuki** [comment]
> > ![图片](https://user-images.githubusercontent.com/15242207/81471601-dba93980-9224-11ea-96a2-a59e3b67ec54.png)
> > 报告错误，谁可以解决
> > 对插件进行如下设置：只勾选“ 5.1音频”并取消勾选“选择最佳比特率"。此方法暂时可用。

thanks

**Comment by jangxx** [comment]
I just sent a PR which fixes the problem by updating to the latest cadmium-playercore version and patching it. I can't really verify if the 5.1 stuff works properly, but at least the video is playing again.

**Comment by starm7md** [comment]
@jangxx  have this error D7354 on Microsoft edge (Chromium build) Version 81.0.416.72 as soon as i play some video it shows error D7354 ,iam on windows 10 the versions aren't the problem because i've tried old and new versions and all of them have the same problem , please begging for help 
![n shoot](https://user-images.githubusercontent.com/65809932/82730911-02c73700-9d0c-11ea-85ae-5c37daf83963.png)
![n shoot 2](https://user-images.githubusercontent.com/65809932/82730913-0490fa80-9d0c-11ea-8dd5-f200e6c7dbd6.png)

**Comment by lkmvip** [comment]
> @jangxx have this error D7354 on Microsoft edge (Chromium build) Version 81.0.416.72 as soon as i play some video it shows error D7354 ,iam on windows 10 the versions aren't the problem because i've tried old and new versions and all of them have the same problem , please begging for help
> ![n shoot](https://user-images.githubusercontent.com/65809932/82730911-02c73700-9d0c-11ea-85ae-5c37daf83963.png)
> ![n shoot 2](https://user-images.githubusercontent.com/65809932/82730913-0490fa80-9d0c-11ea-8dd5-f200e6c7dbd6.png)


edge Chromium build uses different playback cores, specifically cadmium-playercore-*. *. *. 031.js

edge Chromium build can use DDplus, but the version after V79 can not watch 4K，only 1080P，Same as Chrome


![11](https://user-images.githubusercontent.com/12974141/82731412-3a000d00-9d39-11ea-962d-66008ba20f50.png)

**Comment by starm7md** [comment]
@alienx2 1080p is more than enough for me , but i need to find a way to fix this problem, i understand that i need to change   cadmium playercore in order to fix it , can you elaborate and tell me how please

**Comment by truedread** [comment]
Closing as major changes have been made that have probably fixed this.
